name: mrwebbeast
description: Flutter Skeleton using Provider State Management.
publish_to: 'none'
version: 1.0.10+10
environment:
#  sdk: '>=3.1.3 <4.0.0'
#   sdk: '>=3.0.0 <4.0.0'
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  go_router: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.3
  http: ^1.1.0
  http_parser: ^4.0.2
  url_launcher: ^6.1.5
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.2
#  firebase_core: ^2.25.3
  firebase_core: ^2.24.2
#  firebase_crashlytics: ^3.4.13
  firebase_crashlytics: ^3.4.1
#  firebase_analytics: ^10.8.4
  firebase_analytics: ^10.7.2
#  firebase_messaging: ^14.7.14
  firebase_messaging: ^14.0.0
  intl: ^0.18.0
  awesome_notifications: ^0.9.2
  path: ^1.8.2
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder.git
      ref: master
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  webview_flutter: ^4.4.1
  future_progress_dialog: ^0.2.0
  # webview_flutter: ^3.0.4
  device_info_plus: ^9.0.0
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.3.0
  permission_handler: ^11.0.0
  app_settings: ^5.0.0
  pin_code_fields: ^8.0.1
  graphview: ^1.2.0
#  syncfusion_flutter_charts: ^24.1.46+1
#  syncfusion_flutter_core: ^24.1.46
  syncfusion_flutter_charts: ^22.2.9
  syncfusion_flutter_core: ^22.2.9
  flutter_vector_icons: ^2.0.0
  dropdown_search: ^5.0.6
  device_preview: ^1.1.0
  flutter_advanced_switch: ^3.0.1
#  syncfusion_flutter_datagrid_export: ^24.1.47
  dotted_border: ^2.1.0
#  syncfusion_flutter_datagrid: ^24.1.46
  syncfusion_flutter_datagrid_export: ^22.2.9
  syncfusion_flutter_datagrid: ^22.2.9
  percent_indicator: ^4.2.3
  video_player: ^2.8.2
#  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  youtube_player_iframe: ^4.0.4
  syncfusion_flutter_pdfviewer: ^22.2.9
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  auto_orientation: ^2.3.1
  easy_stepper: ^0.8.3
  animate_gradient: ^0.0.2+1
  chewie: ^1.7.5
  intl_phone_field: ^3.2.0
  flip_card: ^0.7.0
  dio: ^5.4.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8


dependency_overrides:
  intl: ^0.18.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Ic_fabicon.png"

flutter_native_splash:
  background_image: assets/images/splash_screen.png
  android_gravity: center
  ios_content_mode: center

  # flutter pub run flutter_native_splash:create

  android_12:
  android: true
  ios: true
  web: true
  fullscreen: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/extraImage/
    - assets/videos/
    - assets/social_link/