name: gaas
description: GARDEN AS A SERVICE.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  go_router: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.3
  http: ^1.0.0
  http_parser: ^4.0.2
  url_launcher: ^6.1.5
  share_plus: ^7.0.0
  shimmer: ^3.0.0
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.5
  firebase_analytics: ^10.0.5
  firebase_messaging: ^14.1.0
  intl: ^0.18.0
  path: ^1.8.2
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder.git
      ref: master
  google_maps_flutter: ^2.2.6
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  webview_flutter: ^4.0.6
  future_progress_dialog: ^0.2.0
  build_runner: ^2.3.3
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.2.19
  dotted_line: ^3.1.0
  percent_indicator: ^4.2.3
  youtube_player_iframe: ^4.0.4
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  lottie: ^2.3.2
  image_cropper: ^5.0.0
  visibility_detector: ^0.4.0+2
  permission_handler: ^10.4.3
  app_settings: ^5.0.0
  file_picker: ^5.5.0
  auto_size_text: ^3.0.0
  flutter_stripe: ^9.4.0
  awesome_notifications: ^0.7.4+1
  camera: ^0.10.5+7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#042a49"
  image: assets/images/ic_launcher.png
  android_gravity: center
  ios_content_mode: center
  # flutter pub run flutter_native_splash:create

  android_12:
  android: true
  ios: true
  web: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/


