// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwL1SzQaRuw0E1gXFF72CYIRzFsEa-jk',
    appId: '1:74297037261:web:cebf8d02afd1001d483484',
    messagingSenderId: '74297037261',
    projectId: 'gaas-us',
    authDomain: 'gaas-us.firebaseapp.com',
    storageBucket: 'gaas-us.appspot.com',
    measurementId: 'G-WK6J7E94MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXnkzMEfhKei-kcOXYd1ZdMUT8HHUQjQ',
    appId: '1:74297037261:android:59b88288f08cc0e2483484',
    messagingSenderId: '74297037261',
    projectId: 'gaas-us',
    storageBucket: 'gaas-us.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsbMos1j0sEqxwfCrdi6u0CefkNEICoU',
    appId: '1:74297037261:ios:70566f719afb36bc483484',
    messagingSenderId: '74297037261',
    projectId: 'gaas-us',
    storageBucket: 'gaas-us.appspot.com',
    androidClientId: '74297037261-ob1vc469ue104n22e1sdv7f1eunlq8k8.apps.googleusercontent.com',
    iosClientId: '74297037261-vtd0vntvgba4p3so9a0njc6nofmaa1cf.apps.googleusercontent.com',
    iosBundleId: 'gaas.us.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsbMos1j0sEqxwfCrdi6u0CefkNEICoU',
    appId: '1:74297037261:ios:92dd3f151cb7efb1483484',
    messagingSenderId: '74297037261',
    projectId: 'gaas-us',
    storageBucket: 'gaas-us.appspot.com',
    androidClientId: '74297037261-ob1vc469ue104n22e1sdv7f1eunlq8k8.apps.googleusercontent.com',
    iosClientId: '74297037261-e709t6tk7jkgfkn99vpp399va0ubeb7c.apps.googleusercontent.com',
    iosBundleId: 'app.gaas.com',
  );
}
