// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmffV4jTUD5DTAH5HYbhoxWnhQKcBj65w',
    appId: '1:179240455941:web:57cc1c4ef27a39d0b3f16c',
    messagingSenderId: '179240455941',
    projectId: 'gtp-app',
    authDomain: 'gtp-app.firebaseapp.com',
    storageBucket: 'gtp-app.appspot.com',
    measurementId: 'G-MPS7B763PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJUwcr1uGQ8vUoIja1ShJuIrWFwmLtAxw',
    appId: '1:179240455941:android:45d3905b0d22df66b3f16c',
    messagingSenderId: '179240455941',
    projectId: 'gtp-app',
    storageBucket: 'gtp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOEwSppNqbjaCe6S5tVXV4fJGfIzEFhH0',
    appId: '1:179240455941:ios:56ddf2d8c134b1f8b3f16c',
    messagingSenderId: '179240455941',
    projectId: 'gtp-app',
    storageBucket: 'gtp-app.appspot.com',
    iosBundleId: 'app.gtp.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOEwSppNqbjaCe6S5tVXV4fJGfIzEFhH0',
    appId: '1:179240455941:ios:fb634569f4b8b8e2b3f16c',
    messagingSenderId: '179240455941',
    projectId: 'gtp-app',
    storageBucket: 'gtp-app.appspot.com',
    iosBundleId: 'app.gtp.com.RunnerTests',
  );
}
