// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_4R8ZkWiTLkFssp_icbu8zfPTkOQvoI',
    appId: '1:105753621770:web:9feb40a9e02fef4ed276f3',
    messagingSenderId: '105753621770',
    projectId: 'mrwebbeast',
    authDomain: 'mrwebbeast.firebaseapp.com',
    storageBucket: 'mrwebbeast.appspot.com',
    measurementId: 'G-L6KZ08DSMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOT__zQlWZN06HEHIZBxROfLzwGjHCl8',
    appId: '1:105753621770:android:7fdfcf54a7875076d276f3',
    messagingSenderId: '105753621770',
    projectId: 'mrwebbeast',
    storageBucket: 'mrwebbeast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jR0caej2JXIkEZ5aGV4MSs1j6E_jIwY',
    appId: '1:105753621770:ios:7bd14ad33027acafd276f3',
    messagingSenderId: '105753621770',
    projectId: 'mrwebbeast',
    storageBucket: 'mrwebbeast.appspot.com',
    iosClientId: '105753621770-l04vh4u87ge4hi1c6cc1tufse0ue6jo0.apps.googleusercontent.com',
    iosBundleId: 'app.developer.mrwebbeast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jR0caej2JXIkEZ5aGV4MSs1j6E_jIwY',
    appId: '1:105753621770:ios:3570cda033313a85d276f3',
    messagingSenderId: '105753621770',
    projectId: 'mrwebbeast',
    storageBucket: 'mrwebbeast.appspot.com',
    iosClientId: '105753621770-ib5kuceovdeln740bu1j33t5s743745l.apps.googleusercontent.com',
    iosBundleId: 'app.developer.mrwebbeast.RunnerTests',
  );
}
